services:  

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-net

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_NAME: mysql
    networks:
      - app-net

#Docker Networks
networks:
  app-net:
